### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Chamelllemon** [Booplicate/MAS-Submods-YouTubeMusic#43] opened 2023-07-17 08:54 UTC
It just randomly gave this today. I updated say something submod with updater submod yesterday so maybe that's the problem

[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
    init python in ytm_utils:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 171, in <module>
    import youtube_dl
SyntaxError: invalid syntax (parser.py, line 86)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
    init python in ytm_utils:
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 171, in <module>
    import youtube_dl
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/__init__.py", line 15, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/options.py", line 8, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/downloader/common.py", line 9, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/compat.py", line 2335, in <module>
SyntaxError: invalid syntax (parser.py, line 86)

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.14
[/code]

**Comment by Booplicate** [comment] 2023-07-18 19:32
Are you sure you installed from the releases and not the source code?

**Comment by Chamelllemon** [comment] 2023-07-19 08:54
Yep, updated again just now to be sure. This showed up, it's probably the same error message (The game works fine again when I remove only the submod)
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
    init python in ytm_utils:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 171, in <module>
    import youtube_dl
SyntaxError: invalid syntax (parser.py, line 86)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
    init python in ytm_utils:
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/YouTube Music/ytm_utils.rpy", line 171, in <module>
    import youtube_dl
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/__init__.py", line 15, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/options.py", line 8, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/downloader/common.py", line 9, in <module>
  File "C:\Users\Nikita\Desktop\DDLC-1.1.1-pc - kopie\renpy\loader.py", line 711, in load_module
    exec code in mod.__dict__
  File "python-packages/youtube_dl/compat.py", line 2335, in <module>
SyntaxError: invalid syntax (parser.py, line 86)

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.14
[/code]

**Comment by Booplicate** [comment] 2023-07-19 19:12
I'm puzzled, can you provide logs from the `log/` folder as well as a screenshot of your `game/python-packages/` folder?

**Comment by ZeitHeld** [comment] 2023-07-20 01:05
I had the same error, once I updated the "Say something" submod. But as I didn't use it much anyways, I removed the submod
yet strange, that it happened

**Comment by Chamelllemon** [comment] 2023-07-21 19:48
![image](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/assets/111662346/cd8a5850-efcc-4491-94ad-22adb9344cef)
![image](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/assets/111662346/87b08eb9-1f36-4ab8-947e-141a2df81b1f)
Like this?

**Comment by Booplicate** [comment] 2023-07-28 15:09
Yes, but for the `log/` folder, I need the files from it, not just a screenshot.

**Comment by PCBoyGames** [comment] 2023-08-22 19:03
Wait a minute.

I remade this for myself, checked [the log.txt in the main folder](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/12412046/log.txt), and I got something that might be important here.

`File "python-packages/youtube_dl/compat.py", line 2335, in <module>`
`File "C:\Games\Doki Doki Literature Club\game\submods\Say Something\lib\html\parser.py", line 86`
  
So then I moved the Say Something submod out from the folder, and MAS loaded YouTube Music properly. Is the HTML parser clashing?

> I had the same error, once I updated the "Say something" submod. But as I didn't use it much anyways, I removed the submod
> yet strange, that it happened

Now I figure it's no coincidence that it errors when both mods are present.

**Comment by dreamscached** [comment] 2023-08-22 19:47
Huh that's interesting... It actually may be the case, I add libs to `sys.path` but after importing I don't revert it. I'll release a fix for that.

Edit: it's weird though, path element is *appended*, but I found what's causing it.
Edit 2: fixed it. Doesn't reproduce after fix, but I managed to reproduce it exactly as @PCBoyGames explained it.

**Comment by dreamscached** [comment] 2023-08-22 20:21
@Booplicate that's more of a quickfix for now but the issue (in my understanding) was caused by `youtube_dl` importing `html` module which was already imported by Say Something and it had a syntax error, that part of the code wasn't used by Say Something but apparently was in use by `youtube_dl` - anyway, the Say Something's version was loaded *before* YoutubeDL's and then `import html` simply returned cached module.

This is critical so hopefully new submod framework will introduce a more isolated dependencies handling, if not I'll work on renaming the module or somehow isolating it in my own way. Anyway, it's resolved from my side, I don't think there is anything in your submod to do to fix the issue. I'm sorry for the trouble caused.

**Comment by Booplicate** [comment] 2023-08-23 21:39
@dreamscached thanks for taking care of this. Question, why are you shipping and importing that py3 lib if you don't use it?

The new framework should allow isolation.

**Comment by dreamscached** [comment] 2023-08-23 21:51
I backported it since the markdown library used it, and it's py3-only and I didn't want to rely on pure regexps. My bad, I couldn't foresee others using it.

I'll review the code and remove the dependency on it.

**Comment by Booplicate** [comment] 2023-08-24 18:00
Ah I see. I think it's fine then, considering we're switching to Python 3 soon.

I will close this since it's resolved on your end.

**Closed as completed by Booplicate** 2023-08-24 18:00 UTC
