### ISSUE TITLE
[Bug] Code appearing in song titles during search.

### ISSUE THREAD

**Issue by Abc2557** [Booplicate/MAS-Submods-YouTubeMusic#15] opened 2020-12-21 23:03 UTC
I do not know all what songs this applies to, but when I’d searched “Servant of Evil Will Cover,” the first song that had popped up appeared to contain a massive amount of code. The scroll bar on the side was extremely small, which shows just how long the wall of code was. Attached to this post is an image of what I’ve described.
![image](https://user-images.githubusercontent.com/53543937/102830154-4c652680-43ae-11eb-8a05-de90e5f7c9e0.jpg)

**Comment by Booplicate** [comment] 2020-12-22 17:25
What's the version of the submod you're using?

**Comment by Abc2557** [comment] 2020-12-22 18:00
v2.9, according to the Submods menu

**Comment by Booplicate** [comment] 2020-12-22 19:52
I can't seem to reproduce this issue. Is only this exact song not working, or is it like that for any song you search? Additionally, can you send me a screenshot of `/game/Submods/YouTube Music` and `submod_log.txt`?

**Comment by Abc2557** [comment] 2020-12-22 20:10
I tried testing other things. When searching "doki doki literature club," the response was normal and the options were all just the normal videos' titles. When searching "capriccio farce mario gagabriel," the response was some error ending with a line of "error: Out of memory" and upon clicking ignore, Monika says something along the lines of "Reading this doesn't seem like the best use of your time, [player]". When searching "yttd prayer" and "yttd clown's song," the response was normal again. When searching "daughter of evil mario gagabriel," the "code in song title" bug appeared again. After just switching tabs to type this then going back onto MAS, the error from "capriccio farce mario gagabriel" appeared within just a few seconds
[submod_log.txt](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/5731822/submod_log.txt)
![youtube music screenshot](https://user-images.githubusercontent.com/53543937/102929060-7cb8cd80-445f-11eb-88d0-76b3c39f694a.png)

**Comment by Booplicate** [comment] 2020-12-22 21:46
Each of those songs worked on my side. Can you put those `rpy` and `rpyc` files from the `YouTube Music` folder in a zip archive and attach here?

**Comment by Abc2557** [comment] 2020-12-22 21:48
All of them or just the "ytm_main" ones?

**Comment by Booplicate** [comment] 2020-12-22 21:49
All of them.

**Comment by Abc2557** [comment] 2020-12-22 21:50
[ytm rpy's and rypc's.zip](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/5732149/ytm.rpy.s.and.rypc.s.zip)

**Comment by Booplicate** [comment] 2020-12-22 21:53
Also, the log says you last launched the game on 21st, but today is 22nd (or 23rd depending on the timezone). Are you sure you sent the right one? Maybe you have 2 MAS installs?

**Comment by Abc2557** [comment] 2020-12-22 21:54
Hm... I do have multiple, but I rarely use the other, and I know I sent the one from my main one, so... not sure what that's about

**Comment by Booplicate** [comment] 2020-12-22 23:06
I have no idea why this happens for you. I was going to improve the searching system, but since I don't know what's causing your issue, I can't be sure if it'll fix it.

Same goes for #14. There's no reason for that. I'd guess it's a sub-issue of this.

I'll keep investigating both of those.

**Comment by Abc2557** [comment] 2020-12-22 23:08
Well, alright! Regardless, thank you for the help, and best of luck finding what’s causing this!

**Comment by Booplicate** [comment] 2021-01-12 14:04
This should be fixed with 24e93df, in the newest release! If your problem remains for some reason, open a new issue.

**Closed by Booplicate** 2021-01-12 14:04 UTC
Labels: bug
